import React, { createContext, useContext, useState, useEffect } from 'react';

// Définition du type pour le contexte de langue
interface LanguageContextProps {
  language: string;
  setLanguage: (language: string) => void;
  t: (key: string) => string;
}

// Création du contexte de langue avec une valeur par défaut
const LanguageContext = createContext<LanguageContextProps>({
  language: 'fr', // Langue par défaut
  setLanguage: () => {},
  t: (key: string) => key, // Retourne la clé si la traduction n'est pas trouvée
});

// Hook personnalisé pour accéder au contexte de langue
const useLanguage = () => useContext(LanguageContext);

// Définition du composant fournisseur de langue
interface LanguageProviderProps {
  children: React.ReactNode;
}

const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<string>(localStorage.getItem('language') || 'fr');

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  // Fonction de traduction
  const t = (key: string): string => {
    try {
      // Vérifie si la langue existe dans les traductions
      if (!translations[language]) {
        console.warn(`Language '${language}' not found in translations.`);
        return key; // Retourne la clé si la langue n'est pas trouvée
      }
      
      // Vérifie si la clé existe dans la langue actuelle
      if (typeof translations[language][key] === 'undefined') {
        console.warn(`Translation key '${key}' not found in language '${language}'.`);
        return key; // Retourne la clé si la traduction n'est pas trouvée
      }
      
      return translations[language][key] || key;
    } catch (error) {
      console.error(`Error translating key '${key}':`, error);
      return key; // Retourne la clé en cas d'erreur
    }
  };

  // Dictionnaires de traduction
  const translations = {
    fr: {
      travelTogether: "Voyagez Ensemble",
      clickToLearnMore: "Cliquez pour en savoir plus sur notre mission et nos services",
      offerTrip: "Proposer un trajet",
      searchTrip: "Rechercher un trajet",
      findTrip: "Trouvez le trajet parfait pour votre prochaine destination",
      departureLocation: "Lieu de départ",
      destination: "Destination",
      departureTime: "Heure de départ",
      reset: "Réinitialiser",
      search: "Rechercher",
      noTripsFound: "Aucun trajet trouvé",
      clickToCreateTrip: "Cliquez ici pour proposer un trajet",
      discoverMap: "Découvrez Constantine sur notre carte interactive",
      reservationDetails: "Détails de la réservation",
      passengerInfo: "Informations passager",
      driverInfo: "Informations conducteur",
      confirmReservation: "Confirmer la réservation",
      cancel: "Annuler",
      saveChanges: "Enregistrer les modifications",
      logout: "Déconnexion",
      giveFeedback: "Donner votre avis",
      submitFeedback: "Envoyer l'avis",
      aboutUs: "À propos de nous",
      ourMission: "Notre mission",
      contactUs: "Contactez-nous",
      login: "Se connecter",
      register: "S'inscrire",
      registerAsDriver: "S'inscrire en tant que conducteur",
      registerAsPassenger: "S'inscrire en tant que passager",
      firstName: "Prénom",
      lastName: "Nom",
      email: "Adresse e-mail",
      password: "Mot de passe",
      alreadyHaveAccount: "Vous avez déjà un compte ?",
      needAccount: "Besoin d'un compte ?",
      termsAndConditions: "J'accepte les termes et conditions",
      invalidEmail: "Adresse e-mail invalide",
      passwordRequired: "Mot de passe requis",
      emailRequired: "Adresse e-mail requise",
      firstNameRequired: "Prénom requis",
      lastNameRequired: "Nom de famille requis",
      passwordTooShort: "Le mot de passe doit contenir au moins 8 caractères",
      passwordConfirmationRequired: "Confirmation du mot de passe requise",
      passwordsDoNotMatch: "Les mots de passe ne correspondent pas",
      acceptTerms: "Veuillez accepter les termes et conditions",
      registerSuccess: "Inscription réussie !",
      loginSuccess: "Connexion réussie !",
      logoutSuccess: "Déconnexion réussie !",
      profileUpdated: "Profil mis à jour avec succès !",
      feedbackSent: "Merci pour votre avis !",
      errorSendingFeedback: "Erreur lors de l'envoi de l'avis.",
      settings: "Paramètres",
      profile: "Profil",
      help: "Aide",
      general: "Général",
      account: "Compte",
      notifications: "Notifications",
      security: "Sécurité",
      display: "Affichage",
      languageSettings: "Paramètres de langue",
      theme: "Thème",
      automatic: "Automatique",
      light: "Clair",
      dark: "Sombre",
      editProfile: "Modifier le profil",
      personalInformation: "Informations personnelles",
      updatePassword: "Modifier le mot de passe",
      currentPassword: "Mot de passe actuel",
      newPassword: "Nouveau mot de passe",
      confirmNewPassword: "Confirmer le nouveau mot de passe",
      updateEmail: "Modifier l'adresse e-mail",
      newEmail: "Nouvelle adresse e-mail",
      confirmNewEmail: "Confirmer la nouvelle adresse e-mail",
      deleteAccount: "Supprimer le compte",
      deleteAccountConfirmation: "Êtes-vous sûr de vouloir supprimer votre compte ?",
      yesDelete: "Oui, supprimer",
      noKeepAccount: "Non, garder le compte",
      accountDeleted: "Compte supprimé avec succès.",
      errorDeletingAccount: "Erreur lors de la suppression du compte.",
      currentPasswordRequired: "Mot de passe actuel requis",
      newEmailRequired: "Nouvelle adresse e-mail requise",
      newEmailInvalid: "Nouvelle adresse e-mail invalide",
      newPasswordsDoNotMatch: "Les nouveaux mots de passe ne correspondent pas",
      newPasswordTooShort: "Le nouveau mot de passe doit contenir au moins 8 caractères",
      emailUpdateSuccess: "Adresse e-mail mise à jour avec succès !",
      passwordUpdateSuccess: "Mot de passe mis à jour avec succès !",
      departureDate: "Date de départ",
      departure: "Départ",
      arrival: "Arrivée",
      price: "Prix",
      seatsAvailable: "Places disponibles",
      driver: "Conducteur",
      bookNow: "Réserver maintenant",
      chatWithDriver: "Discuter avec le conducteur",
      availableSeats: "Places disponibles :",
      seat: "place",
      seats: "places",
      details: "Détails",
      date: "Date",
      time: "Heure",
      location: "Lieu",
      distance: "Distance",
      duration: "Durée",
      estimatedArrivalTime: "Heure d'arrivée estimée",
      vehicle: "Véhicule",
      preferences: "Préférences",
      music: "Musique",
      smoking: "Fumeur",
      pets: "Animaux",
      luggage: "Bagages",
      submit: "Envoyer",
      message: "Message",
      typeMessage: "Tapez votre message...",
      sendMessage: "Envoyer le message",
      communityChat: "Chat Communautaire",
      globalChat: "Chat Global",
      askQuestion: "Posez votre question ou partagez vos pensées...",
      noMessages: "Aucun message pour le moment.",
      beFirstToPost: "Soyez le premier à poster !",
      createTrip: "Créer un Trajet",
      startLocation: "Lieu de départ",
      endLocation: "Lieu d'arrivée",
      selectDate: "Sélectionner une date",
      selectTime: "Sélectionner une heure",
      enterPrice: "Entrer le prix",
      enterAvailableSeats: "Entrer le nombre de places disponibles",
      describeTrip: "Décrire le trajet",
      create: "Créer",
      tripCreatedSuccessfully: "Trajet créé avec succès!",
      errorCreatingTrip: "Erreur lors de la création du trajet.",
      editTrip: "Modifier le Trajet",
      updateTrip: "Mettre à jour le Trajet",
      tripUpdatedSuccessfully: "Trajet mis à jour avec succès!",
      errorUpdatingTrip: "Erreur lors de la mise à jour du trajet.",
      deleteTrip: "Supprimer le Trajet",
      confirmDeleteTrip: "Êtes-vous sûr de vouloir supprimer ce trajet?",
      tripDeletedSuccessfully: "Trajet supprimé avec succès!",
      errorDeletingTrip: "Erreur lors de la suppression du trajet.",
      cancelTrip: "Annuler le Trajet",
      confirmCancelTrip: "Êtes-vous sûr de vouloir annuler ce trajet?",
      tripCancelledSuccessfully: "Trajet annulé avec succès!",
      errorCancellingTrip: "Erreur lors de l'annulation du trajet.",
      endLocationRequired: "Lieu d'arrivée requis",
      startLocationRequired: "Lieu de départ requis",
      priceRequired: "Prix requis",
      seatsRequired: "Nombre de places requis",
      dateRequired: "Date requise",
      timeRequired: "Heure requise",
      descriptionRequired: "Description requise",
      invalidPrice: "Prix invalide",
      invalidSeats: "Nombre de places invalide",
      invalidDate: "Date invalide",
      invalidTime: "Heure invalide",
      invalidDescription: "Description invalide",
      searchHelpTitle: "Comment rechercher un trajet?",
      searchHelpDescription: "Voici quelques conseils pour trouver le trajet parfait.",
      searchHelpTip1: "Utilisez des mots-clés précis pour le lieu de départ et d'arrivée.",
      searchHelpTip2: "Sélectionnez la date et l'heure souhaitées pour affiner votre recherche.",
      searchHelpTip3: "Consultez les détails du trajet pour connaître les préférences du conducteur.",
      searchHelpTip4: "Contactez le conducteur pour toute question avant de réserver.",
      searchHelpTip5: "Vérifiez les avis des autres passagers avant de faire votre choix.",
      downloadApp: "Téléchargez notre application mobile",
      scanToDownload: "Scannez le code QR pour télécharger l'application mobile Wassalni",
      downloadNow: "Télécharger maintenant",
    },
    ar: {
      travelTogether: "نسافر معًا",
      clickToLearnMore: "انقر لمعرفة المزيد عن مهمتنا وخدماتنا",
      offerTrip: "اعرض رحلة",
      searchTrip: "ابحث عن رحلة",
      findTrip: "ابحث عن الرحلة المثالية لوجهتك القادمة",
      departureLocation: "مكان المغادرة",
      destination: "الوجهة",
      departureTime: "وقت المغادرة",
      reset: "إعادة تعيين",
      search: "بحث",
      noTripsFound: "لم يتم العثور على رحلات",
      clickToCreateTrip: "انقر هنا لعرض رحلة",
      discoverMap: "اكتشف قسنطينة على خريطتنا التفاعلية",
      reservationDetails: "تفاصيل الحجز",
      passengerInfo: "معلومات الراكب",
      driverInfo: "معلومات السائق",
      confirmReservation: "تأكيد الحجز",
      cancel: "إلغاء",
      saveChanges: "حفظ التغييرات",
      logout: "تسجيل الخروج",
      giveFeedback: "إعطاء ملاحظات",
      submitFeedback: "إرسال الملاحظات",
      aboutUs: "معلومات عنا",
      ourMission: "مهمتنا",
      contactUs: "اتصل بنا",
      login: "تسجيل الدخول",
      register: "تسجيل",
      registerAsDriver: "التسجيل كسائق",
      registerAsPassenger: "التسجيل كراكب",
      firstName: "الاسم الأول",
      lastName: "اسم العائلة",
      email: "عنوان البريد الإلكتروني",
      password: "كلمة المرور",
      alreadyHaveAccount: "هل لديك حساب بالفعل؟",
      needAccount: "هل تحتاج إلى حساب؟",
      termsAndConditions: "أوافق على الشروط والأحكام",
      invalidEmail: "عنوان بريد إلكتروني غير صالح",
      passwordRequired: "كلمة المرور مطلوبة",
      emailRequired: "عنوان البريد الإلكتروني مطلوب",
      firstNameRequired: "الاسم الأول مطلوب",
      lastNameRequired: "اسم العائلة مطلوب",
      passwordTooShort: "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل",
      passwordConfirmationRequired: "تأكيد كلمة المرور مطلوب",
      passwordsDoNotMatch: "كلمات المرور غير متطابقة",
      acceptTerms: "يرجى قبول الشروط والأحكام",
      registerSuccess: "تم التسجيل بنجاح!",
      loginSuccess: "تم تسجيل الدخول بنجاح!",
      logoutSuccess: "تم تسجيل الخروج بنجاح!",
      profileUpdated: "تم تحديث الملف الشخصي بنجاح!",
      feedbackSent: "شكرا لك على ملاحظاتك!",
      errorSendingFeedback: "خطأ في إرسال الملاحظات.",
      settings: "إعدادات",
      profile: "الملف الشخصي",
      help: "مساعدة",
      general: "عام",
      account: "الحساب",
      notifications: "إشعارات",
      security: "الأمان",
      display: "عرض",
      languageSettings: "إعدادات اللغة",
      theme: "السمة",
      automatic: "تلقائي",
      light: "فاتح",
      dark: "داكن",
      editProfile: "تعديل الملف الشخصي",
      personalInformation: "معلومات شخصية",
      updatePassword: "تحديث كلمة المرور",
      currentPassword: "كلمة المرور الحالية",
      newPassword: "كلمة المرور الجديدة",
      confirmNewPassword: "تأكيد كلمة المرور الجديدة",
      updateEmail: "تحديث عنوان البريد الإلكتروني",
      newEmail: "عنوان البريد الإلكتروني الجديد",
      confirmNewEmail: "تأكيد عنوان البريد الإلكتروني الجديد",
      deleteAccount: "حذف الحساب",
      deleteAccountConfirmation: "هل أنت متأكد أنك تريد حذف حسابك؟",
      yesDelete: "نعم، احذف",
      noKeepAccount: "لا، احتفظ بالحساب",
      accountDeleted: "تم حذف الحساب بنجاح.",
      errorDeletingAccount: "خطأ في حذف الحساب.",
      currentPasswordRequired: "كلمة المرور الحالية مطلوبة",
      newEmailRequired: "عنوان البريد الإلكتروني الجديد مطلوب",
      newEmailInvalid: "عنوان بريد إلكتروني جديد غير صالح",
      newPasswordsDoNotMatch: "كلمات المرور الجديدة غير متطابقة",
      newPasswordTooShort: "يجب أن تتكون كلمة المرور الجديدة من 8 أحرف على الأقل",
      emailUpdateSuccess: "تم تحديث عنوان البريد الإلكتروني بنجاح!",
      passwordUpdateSuccess: "تم تحديث كلمة المرور بنجاح!",
      departureDate: "تاريخ المغادرة",
      departure: "المغادرة",
      arrival: "الوصول",
      price: "السعر",
      seatsAvailable: "المقاعد المتاحة",
      driver: "السائق",
      bookNow: "احجز الآن",
      chatWithDriver: "الدردشة مع السائق",
      availableSeats: "المقاعد المتاحة:",
      seat: "مقعد",
      seats: "مقاعد",
      details: "التفاصيل",
      date: "التاريخ",
      time: "الوقت",
      location: "الموقع",
      distance: "المسافة",
      duration: "المدة",
      estimatedArrivalTime: "وقت الوصول المقدر",
      vehicle: "المركبة",
      preferences: "التفضيلات",
      music: "موسيقى",
      smoking: "تدخين",
      pets: "الحيوانات الأليفة",
      luggage: "الأمتعة",
      submit: "إرسال",
      message: "رسالة",
      typeMessage: "اكتب رسالتك...",
      sendMessage: "إرسال الرسالة",
      communityChat: "دردشة مجتمعية",
      globalChat: "دردشة عالمية",
      askQuestion: "اطرح سؤالك أو شارك أفكارك...",
      noMessages: "لا توجد رسائل حتى الآن.",
      beFirstToPost: "كن أول من ينشر!",
      createTrip: "إنشاء رحلة",
      startLocation: "مكان البداية",
      endLocation: "مكان النهاية",
      selectDate: "اختر تاريخ",
      selectTime: "اختر وقت",
      enterPrice: "أدخل السعر",
      enterAvailableSeats: "أدخل عدد المقاعد المتاحة",
      describeTrip: "وصف الرحلة",
      create: "إنشاء",
      tripCreatedSuccessfully: "تم إنشاء الرحلة بنجاح!",
      errorCreatingTrip: "خطأ في إنشاء الرحلة.",
      editTrip: "تعديل الرحلة",
      updateTrip: "تحديث الرحلة",
      tripUpdatedSuccessfully: "تم تحديث الرحلة بنجاح!",
      errorUpdatingTrip: "خطأ في تحديث الرحلة.",
      deleteTrip: "حذف الرحلة",
      confirmDeleteTrip: "هل أنت متأكد أنك تريد حذف هذه الرحلة؟",
      tripDeletedSuccessfully: "تم حذف الرحلة بنجاح!",
      errorDeletingTrip: "خطأ في حذف الرحلة.",
      cancelTrip: "إلغاء الرحلة",
      confirmCancelTrip: "هل أنت متأكد أنك تريد إلغاء هذه الرحلة؟",
      tripCancelledSuccessfully: "تم إلغاء الرحلة بنجاح!",
      errorCancellingTrip: "خطأ في إلغاء الرحلة.",
      endLocationRequired: "مكان النهاية مطلوب",
      startLocationRequired: "مكان البداية مطلوب",
      priceRequired: "السعر مطلوب",
      seatsRequired: "عدد المقاعد مطلوب",
      dateRequired: "التاريخ مطلوب",
      timeRequired: "الوقت مطلوب",
      descriptionRequired: "الوصف مطلوب",
      invalidPrice: "سعر غير صالح",
      invalidSeats: "عدد مقاعد غير صالح",
      invalidDate: "تاريخ غير صالح",
      invalidTime: "وقت غير صالح",
      invalidDescription: "وصف غير صالح",
      searchHelpTitle: "كيف تبحث عن رحلة؟",
      searchHelpDescription: "إليك بعض النصائح للعثور على الرحلة المثالية.",
      searchHelpTip1: "استخدم كلمات مفتاحية دقيقة لمكان المغادرة والوصول.",
      searchHelpTip2: "حدد التاريخ والوقت المطلوبين لتضييق نطاق البحث.",
      searchHelpTip3: "راجع تفاصيل الرحلة لمعرفة تفضيلات السائق.",
      searchHelpTip4: "اتصل بالسائق لطرح أي أسئلة قبل الحجز.",
      searchHelpTip5: "تحقق من تقييمات الركاب الآخرين قبل اتخاذ قرارك.",
      downloadApp: "حمّل تطبيقنا للهاتف المحمول",
      scanToDownload: "امسح رمز QR لتنزيل تطبيق وصلني للهاتف المحمول",
      downloadNow: "التنزيل الآن",
    },
    en: {
      travelTogether: "Travel Together",
      clickToLearnMore: "Click to learn more about our mission and services",
      offerTrip: "Offer a Trip",
      searchTrip: "Search for a Trip",
      findTrip: "Find the perfect trip for your next destination",
      departureLocation: "Departure Location",
      destination: "Destination",
      departureTime: "Departure Time",
      reset: "Reset",
      search: "Search",
      noTripsFound: "No trips found",
      clickToCreateTrip: "Click here to offer a trip",
      discoverMap: "Discover Constantine on our interactive map",
      reservationDetails: "Reservation Details",
      passengerInfo: "Passenger Information",
      driverInfo: "Driver Information",
      confirmReservation: "Confirm Reservation",
      cancel: "Cancel",
      saveChanges: "Save Changes",
      logout: "Logout",
      giveFeedback: "Give Feedback",
      submitFeedback: "Submit Feedback",
      aboutUs: "About Us",
      ourMission: "Our Mission",
      contactUs: "Contact Us",
      login: "Login",
      register: "Register",
      registerAsDriver: "Register as Driver",
      registerAsPassenger: "Register as Passenger",
      firstName: "First Name",
      lastName: "Last Name",
      email: "Email Address",
      password: "Password",
      alreadyHaveAccount: "Already have an account?",
      needAccount: "Need an account?",
      termsAndConditions: "I accept the terms and conditions",
      invalidEmail: "Invalid email address",
      passwordRequired: "Password required",
      emailRequired: "Email required",
      firstNameRequired: "First name required",
      lastNameRequired: "Last name required",
      passwordTooShort: "Password must be at least 8 characters",
      passwordConfirmationRequired: "Password confirmation required",
      passwordsDoNotMatch: "Passwords do not match",
      acceptTerms: "Please accept the terms and conditions",
      registerSuccess: "Registration successful!",
      loginSuccess: "Login successful!",
      logoutSuccess: "Logout successful!",
      profileUpdated: "Profile updated successfully!",
      feedbackSent: "Thank you for your feedback!",
      errorSendingFeedback: "Error sending feedback.",
      settings: "Settings",
      profile: "Profile",
      help: "Help",
      general: "General",
      account: "Account",
      notifications: "Notifications",
      security: "Security",
      display: "Display",
      languageSettings: "Language Settings",
      theme: "Theme",
      automatic: "Automatic",
      light: "Light",
      dark: "Dark",
      editProfile: "Edit Profile",
      personalInformation: "Personal Information",
      updatePassword: "Update Password",
      currentPassword: "Current Password",
      newPassword: "New Password",
      confirmNewPassword: "Confirm New Password",
      updateEmail: "Update Email",
      newEmail: "New Email",
      confirmNewEmail: "Confirm New Email",
      deleteAccount: "Delete Account",
      deleteAccountConfirmation: "Are you sure you want to delete your account?",
      yesDelete: "Yes, delete",
      noKeepAccount: "No, keep account",
      accountDeleted: "Account deleted successfully.",
      errorDeletingAccount: "Error deleting account.",
      currentPasswordRequired: "Current password required",
      newEmailRequired: "New email required",
      newEmailInvalid: "New email invalid",
      newPasswordsDoNotMatch: "New passwords do not match",
      newPasswordTooShort: "New password must be at least 8 characters",
      emailUpdateSuccess: "Email updated successfully!",
      passwordUpdateSuccess: "Password updated successfully!",
      departureDate: "Departure Date",
      departure: "Departure",
      arrival: "Arrival",
      price: "Price",
      seatsAvailable: "Seats Available",
      driver: "Driver",
      bookNow: "Book Now",
      chatWithDriver: "Chat with Driver",
      availableSeats: "Available Seats:",
      seat: "seat",
      seats: "seats",
      details: "Details",
      date: "Date",
      time: "Time",
      location: "Location",
      distance: "Distance",
      duration: "Duration",
      estimatedArrivalTime: "Estimated Arrival Time",
      vehicle: "Vehicle",
      preferences: "Preferences",
      music: "Music",
      smoking: "Smoking",
      pets: "Pets",
      luggage: "Luggage",
      submit: "Submit",
      message: "Message",
      typeMessage: "Type your message...",
      sendMessage: "Send Message",
      communityChat: "Community Chat",
      globalChat: "Global Chat",
      askQuestion: "Ask your question or share your thoughts...",
      noMessages: "No messages yet.",
      beFirstToPost: "Be the first to post!",
      createTrip: "Create a Trip",
      startLocation: "Start Location",
      endLocation: "End Location",
      selectDate: "Select a Date",
      selectTime: "Select a Time",
      enterPrice: "Enter the Price",
      enterAvailableSeats: "Enter the Number of Available Seats",
      describeTrip: "Describe the Trip",
      create: "Create",
      tripCreatedSuccessfully: "Trip created successfully!",
      errorCreatingTrip: "Error creating the trip.",
      editTrip: "Edit Trip",
      updateTrip: "Update Trip",
      tripUpdatedSuccessfully: "Trip updated successfully!",
      errorUpdatingTrip: "Error updating the trip.",
      deleteTrip: "Delete Trip",
      confirmDeleteTrip: "Are you sure you want to delete this trip?",
      tripDeletedSuccessfully: "Trip deleted successfully!",
      errorDeletingTrip: "Error deleting the trip.",
      cancelTrip: "Cancel Trip",
      confirmCancelTrip: "Are you sure you want to cancel this trip?",
      tripCancelledSuccessfully: "Trip cancelled successfully!",
      errorCancellingTrip: "Error cancelling the trip.",
      endLocationRequired: "End location required",
      startLocationRequired: "Start location required",
      priceRequired: "Price required",
      seatsRequired: "Number of seats required",
      dateRequired: "Date required",
      timeRequired: "Time required",
      descriptionRequired: "Description required",
      invalidPrice: "Invalid price",
      invalidSeats: "Invalid number of seats",
      invalidDate: "Invalid date",
      invalidTime: "Invalid time",
      invalidDescription: "Invalid description",
      searchHelpTitle: "How to search for a trip?",
      searchHelpDescription: "Here are some tips to find the perfect trip.",
      searchHelpTip1: "Use precise keywords for the departure and arrival locations.",
      searchHelpTip2: "Select the desired date and time to refine your search.",
      searchHelpTip3: "Check the trip details to know the driver's preferences.",
      searchHelpTip4: "Contact the driver with any questions before booking.",
      searchHelpTip5: "Check the reviews of other passengers before making your choice.",
      downloadApp: "Download our mobile app",
      scanToDownload: "Scan the QR code to download the Wassalni mobile app",
      downloadNow: "Download now",
    },
  };

  const value = { language, setLanguage, t };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export { LanguageContext, LanguageProvider, useLanguage };
