// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eapailcwzemhojmrnyuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhcGFpbGN3emVtaG9qbXJueXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNDk4MjYsImV4cCI6MjA1NjkyNTgyNn0.SOhQjNqbN8TzFGPUJAF0MgVSQpHvJjDqc3m53tiRfBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);